using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

namespace Boss.LookDev.Editor.Ops
{
    /// <summary>
    /// (B) Stylized background + ambient (spec §3.2). Realizes BackgroundSection so
    /// a look fully owns how the environment reads — e.g. deep-sea VR: solid or
    /// vertical-gradient blue background + colored flat/gradient ambient — making
    /// it reproducible from the asset alone. The gradient sky is a generated
    /// skybox shader/material (pipeline-agnostic), like the ground-shadow shader.
    /// </summary>
    public static class BackgroundOps
    {
        public static void Apply(LookDefinition look)
        {
            var bg = look != null ? look.background : null;
            if (bg == null || !bg.enabled) return;

            // Ambient (indirect light)
            switch (bg.ambientMode)
            {
                case LookAmbientMode.Skybox:
                    RenderSettings.ambientMode = AmbientMode.Skybox;
                    break;
                case LookAmbientMode.Flat:
                    RenderSettings.ambientMode = AmbientMode.Flat;
                    RenderSettings.ambientLight = bg.ambientFlat;
                    break;
                case LookAmbientMode.Gradient:
                    RenderSettings.ambientMode = AmbientMode.Trilight;
                    RenderSettings.ambientSkyColor = bg.ambientSky;
                    RenderSettings.ambientEquatorColor = bg.ambientEquator;
                    RenderSettings.ambientGroundColor = bg.ambientGround;
                    break;
            }
            RenderSettings.ambientIntensity = bg.ambientIntensity;

            // Background (camera)
            var cam = Camera.main;
            switch (bg.mode)
            {
                case BackgroundMode.Skybox:
                    // Restore the HDRI skybox material into RenderSettings (it may
                    // have been nulled by a previous SolidColor/AR switch).
                    var hdriMat = AssetDatabase.LoadAssetAtPath<Material>(
                        $"{SceneBindingOps.AssetFolder(look)}/{look.lookName}_Skybox.mat");
                    if (hdriMat != null) RenderSettings.skybox = hdriMat;
                    if (cam != null) cam.clearFlags = CameraClearFlags.Skybox;
                    break;
                case BackgroundMode.SolidColor:
                    // Actually remove the Lighting skybox (not just the camera) so
                    // STYLY / AR genuinely has no sky. Baked ambient/reflection stay.
                    RenderSettings.skybox = null;
                    if (cam != null)
                    {
                        cam.clearFlags = CameraClearFlags.SolidColor;
                        cam.backgroundColor = bg.solidColor; // alpha 0 => AR transparent
                        EditorUtility.SetDirty(cam);
                    }
                    break;
                case BackgroundMode.Gradient:
                    var mat = EnsureGradientSkybox(look);
                    if (mat != null)
                    {
                        RenderSettings.skybox = mat;
                        if (cam != null) cam.clearFlags = CameraClearFlags.Skybox;
                    }
                    break;
            }
            DynamicGI.UpdateEnvironment();
        }

        private static Material EnsureGradientSkybox(LookDefinition look)
        {
            var bg = look.background;
            var shader = EnsureGradientShader(look);
            if (shader == null) { Debug.LogError("[BOSS Look Dev] グラデーション空シェーダ生成失敗。"); return null; }

            string folder = SceneBindingOps.AssetFolder(look);
            string matPath = $"{folder}/{look.lookName}_GradientSky.mat";
            var mat = AssetDatabase.LoadAssetAtPath<Material>(matPath);
            if (mat == null) { mat = new Material(shader); AssetDatabase.CreateAsset(mat, matPath); }
            else if (mat.shader != shader) mat.shader = shader;
            mat.SetColor("_Top", bg.gradientTop);
            mat.SetColor("_Bottom", bg.gradientBottom);
            mat.SetFloat("_Exp", Mathf.Max(0.2f, bg.gradientExponent));
            EditorUtility.SetDirty(mat);
            AssetDatabase.SaveAssets();
            return mat;
        }

        private static Shader EnsureGradientShader(LookDefinition look)
        {
            string folder = SceneBindingOps.AssetFolder(look);
            string shaderPath = $"{folder}/{look.lookName}_GradientSky.shader";
            if (!File.Exists(shaderPath) || File.ReadAllText(shaderPath) != GradientShaderSource)
            {
                File.WriteAllText(shaderPath, GradientShaderSource);
                AssetDatabase.ImportAsset(shaderPath);
            }
            return AssetDatabase.LoadAssetAtPath<Shader>(shaderPath);
        }

        // Vertical gradient skybox. Works in Built-in and URP (skybox pass).
        private const string GradientShaderSource = @"// Auto-generated by BOSS Look Dev (gradient skybox).
Shader ""BOSS/GradientSky""
{
    Properties
    {
        _Top (""Top"", Color) = (0.10, 0.30, 0.38, 1)
        _Bottom (""Bottom"", Color) = (0.01, 0.05, 0.08, 1)
        _Exp (""Exponent"", Float) = 1
    }
    SubShader
    {
        Tags { ""Queue"" = ""Background"" ""RenderType"" = ""Background"" ""PreviewType"" = ""Skybox"" }
        Cull Off ZWrite Off
        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include ""UnityCG.cginc""
            struct appdata { float4 vertex : POSITION; };
            struct v2f { float4 pos : SV_POSITION; float3 dir : TEXCOORD0; };
            half4 _Top; half4 _Bottom; float _Exp;
            v2f vert(appdata v) { v2f o; o.pos = UnityObjectToClipPos(v.vertex); o.dir = v.vertex.xyz; return o; }
            half4 frag(v2f i) : SV_Target
            {
                float t = saturate(normalize(i.dir).y * 0.5 + 0.5);
                return lerp(_Bottom, _Top, pow(t, _Exp));
            }
            ENDCG
        }
    }
    Fallback Off
}
";
    }
}
